Check that programs are found before use
Currently help2man and valgrind are not checks to be present before
being used. That leads to some cryptic error messages (especially for
the help2man). Check if they exist before use and print sensible error
message.

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -25,7 +25,11 @@ GGO_FILES = $(srcdir)/sample1.ggo $(srcdir)/sample2.ggo
 man_MANS = gengetopt.1
 
 gengetopt.1: $(top_srcdir)/src/cmdline.ggo
-	$(HELP2MAN) $(PROGNAME) --help-option="--detailed-help" > $@
+	@if test x"$(HELP2MAN)" == x":"; then \
+		echo >&2 "Error: help2man is required to create $@"; \
+		exit 1; \
+	fi
+	$(HELP2MAN) --help-option="--detailed-help" -- $(PROGNAME) > $@
 
 
 EXTRA_PROGRAMS = sample1 sample2
diff --git a/tests/valgrind_suppressions.sh.in b/tests/valgrind_suppressions.sh.in
--- a/tests/valgrind_suppressions.sh.in
+++ b/tests/valgrind_suppressions.sh.in
@@ -10,6 +10,10 @@
 #
 # --------------------------------------------------------------------- #
 
+if test x"@VALGRIND@" = ":"; then
+	echo >&2 "valgrind is required to run this"
+	exit 1
+fi
 
 VG_PRG="@VALGRIND@"
 VG_ARGS="--tool=memcheck --num-callers=20 --leak-check=yes --leak-resolution=high --show-reachable=yes --suppressions=@srcdir@/suppressions.supp --gen-suppressions=yes"
diff --git a/tests/valgrind_tests.sh.in b/tests/valgrind_tests.sh.in
--- a/tests/valgrind_tests.sh.in
+++ b/tests/valgrind_tests.sh.in
@@ -11,11 +11,10 @@
 #
 # --------------------------------------------------------------------- #
 
-
-# Hack to run valgrind with new glibcs.  Problem: new TLS (thread
-# local storage)
-
-#VG_ENV="LD_ASSUME_KERNEL=2.2.5"
+if test x"@VALGRIND@" = ":"; then
+	echo >&2 "valgrind is required to run this"
+	exit 1
+fi
 
 VG_PRG="@VALGRIND@"
 VG_ARGS="--tool=memcheck --num-callers=20 --leak-check=yes --leak-resolution=high --show-reachable=yes --suppressions=@srcdir@/suppressions.supp"
